name: SonarLess Scan
description: SonarLess Scan Action
inputs:
  sonar-project-name:
    description: "SonarQube Project Name"
    required: false
    default: ${{github.event.repository.name}}
  sonar-project-key:
    description: "SonarQube Project Key"
    required: false
    default: ${{github.event.repository.name}}
  sonar-source-path:
    description: "Path to the source code"
    required: false
    default: "src"
  sonar-metrics-path:
    description: "Path to the metrics file"
    required: false
    default: "./sonar-metrics.json"
  is-sonar-metrics-upload:
    description: "Upload Sonar metrics"
    required: false
    default: "true"
  github-token:
    description: "GitHub token for posting PR comments."
    required: false
    default: ${{ github.token }}
  dotnet-build-command:
    description: "Command to build the .NET project (e.g., 'dotnet build'). Required for .NET scanning."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set Script Permissions
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/makefile.sh
        chmod +x ${{ github.action_path }}/scripts/check_quality_gate.sh

    - name: Get Docker Dependencies
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/makefile.sh docker-deps-get
        ${{ github.action_path }}/scripts/makefile.sh sonar-ext-get

    - name: Run Sonarless
      shell: bash
      run: |
        if [[ -n "${{ inputs.dotnet-build-command }}" ]]; then
          ${{ github.action_path }}/scripts/makefile.sh dotnet-scan
        else
          ${{ github.action_path }}/scripts/makefile.sh scan
        fi
      env:
        DOTNET_BUILD_COMMAND: ${{ inputs.dotnet-build-command }}
        SONAR_PROJECT_NAME: ${{inputs.sonar-project-name}}
        SONAR_PROJECT_KEY: ${{inputs.sonar-project-key}}
        SONAR_SOURCE_PATH: ${{inputs.sonar-source-path}}
        SONAR_METRICS_PATH: ${{inputs.sonar-metrics-path}}
        SONAR_GITROOT: ${{ github.workspace }}

    - name: Get Sonar Results
      shell: bash
      run: ${{ github.action_path }}/scripts/makefile.sh results
      env:
        SONAR_PROJECT_NAME: ${{inputs.sonar-project-name}}
        SONAR_PROJECT_KEY: ${{inputs.sonar-project-key}}
        SONAR_SOURCE_PATH: ${{inputs.sonar-source-path}}
        SONAR_METRICS_PATH: ${{inputs.sonar-metrics-path}}
        SONAR_GITROOT: ${{ github.workspace }}

    - name: Upload Sonar metrics
      if: ${{ inputs.is-sonar-metrics-upload == 'true' }}
      uses: actions/upload-artifact@v6
      with:
        name: sonar-metrics
        path: ${{inputs.sonar-metrics-path}}

    - name: Post PR Comment with Findings
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/makefile.sh post-pr-comment
      env:
        SONAR_PROJECT_NAME: ${{inputs.sonar-project-name}}
        SONAR_PROJECT_KEY: ${{inputs.sonar-project-key}}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        PR_NUMBER: ${{ github.event.pull_request.number }}

    - name: Check Sonar Metrics - No Vulnerabilities
      shell: bash
      env:
        METRICS_PATH: ${{inputs.sonar-metrics-path}}
        QUALITY_GATE_PATH: ${{ github.action_path }}/scripts/quality-gate.json
      run: bash ${{ github.action_path }}/scripts/check_quality_gate.sh
